### ISSUE TITLE
Merging our projects.

### ISSUE THREAD

**Issue by jamen** [audio-lab/contributing#18]
I think it is in everyone's interests here to create a universal framework of audio inside of JavaScript, which I think would be something amazing and fun to create and collaborate on with other people (And you seem to have some very good work done here already)

If you are interested in this: I'm willing to come to a compromise with the names `audiojs` on GitHub and `audio` on npm, as long as I still retain some ownership over whatever project comes out of them (as I would love to collaborate on that with you and others).  For example: transferring repos from here over there, renaming this organization, or an alternative project for `audiojs`.  I would like to remain one of the owners throughout it, but I'm not against having other owners to collaborate with.

If that idea sounds good, let me know if you'd like an invite as an owner to the `audiojs` organization.  Or if you have other ideas or concerns for the future of these projects in mind then feel free to tell me, as I'm open to ideas.

The last thing I want is fragmented packages for audio in JavaScript, especially with our projects being similar in nature.

**Comment by dfcreative** [comment]
I am totally for such framework, there is a room for that. Having an audio toolset for node & browser would be sweet. All the more if components will have CLI APIs, to use them through unix pipes, eg `cat sound.wav | filter --lowpass 200 > filtered.wav`. Even more, to have gulp-like tool for audio, e.g. to create audio mastering pipelines based on _"gulpfile.js"_, like `cat record.wav | master --voice --format mp3 > result.mp3` etc, that is whan eventually I am trying to come up with one day).

So sure, having agreement on names would really facilitate work, as right now `audio-*` components in npm not always have CLI/node/stream APIs.

_audio-js_ is a very loud and serious name, as a big collection of modules, like [component](https://github.com/component), but for audio. Suffix `-js` is a bit out though, just _audio_ would be perfect, but the name is occupied.
_audio-lab_ is just a experimental name, reflecting the type of projects here.

If you feel like I can care of some of _audiojs_ projects - sure, send me an invite.

**Comment by jamen** [comment]
Awesome ideas, those are some I've actually had as well!  Partially the reason I wanted to design off streams so it would be easier to accomplish with things like `process.stdin` and `process.stdout`.  Glad we are on the same page.

**Comment by dfcreative** [comment]
Well sounds good, I think we can try to merge some projects into audiojs. Here is a bit of experimental stuff, but I am sure most of the packages will be good there.

**Comment by dfcreative** [comment]
Nope :( Links are going to be a massive work! Like every _package.json_, every demo in gh-pages etc etc...

**Comment by jamen** [comment]
I know that GitHub redirects transferred repositories and renamed organizations at the least, but it wont do gh-pages.

**Comment by dfcreative** [comment]
Anyways I have to update there components, I was planning to connect greenkeeper for that.
Some revision:

* [ ] [web-audio-stream](https://github.com/audio-lab/web-audio-stream)
* [ ] [audio-speaker](https://github.com/audio-lab/audio-speaker)
* [ ] [audio-through](https://github.com/audio-lab/audio-through)
* [ ] [audio-pcm-format](https://github.com/audio-lab/audio-pcm-format)
* [ ] [audio-buffer](https://github.com/audio-lab/audio-buffer)
* [ ] [audio-gail](https://github.com/audio-lab/audio-gain)
* [ ] [audio-oscillator](https://github.com/audio-lab/audio-oscillator)
* [ ] [audio-slice](https://github.com/audio-lab/audio-slice)
* [ ] [audio-sink](https://github.com/audio-lab/audio-sink)
* [ ] [audio-generator](https://github.com/audio-lab/audio-generator)
* [ ] [audio-biquad](https://github.com/audio-lab/audio-biquad)
* [ ] [pcm-util](https://github.com/audio-lab/pcm-util) ?
* [ ] [is-audio-buffer](https://github.com/audio-lab/is-audio-buffer) ?
* [ ] [audio-table](https://github.com/audio-lab/audio-table) WIP
* [ ] [audio-mixer](https://github.com/audio-lab/mixer)

**Comment by jamen** [comment]
I'd like to do some pull requests to help with those.

And by the way, do you mean you want to change them over to `audio` or keep their dependencies the same?  I'm curious how `audio` will play in all of this, if you wanted to use the name or rework the components you have to use it.

**Comment by dfcreative** [comment]
I want to transfer these components to @audiojs completely, without serious changes.
_audio_ is a nice container for userland, like audio-editing components, but I think keeping minimally valid container for streaming components is better due to performance. In this case I would opt for `audio-buffer`, which is in node is a holder for `FloatArray` and for browser is builtin _AudioBuffer_ class. Also unlike _Buffer_, it can be transfered by reference between streams, therefore will not eat processor’s time on recoding, what may easily happen with raw PCM data.

**Comment by jamen** [comment]
I can agree with that.  Sounds good.  Lots of components for me to learn tonight.  :p

**Comment by dfcreative** [comment]
Moved those that it is a better place.
It is not necessary to learn all of them off the bat, rather revising the docs and creating user-view issues. That is really valuable to make readme’s neat, tiny and easy to understand.

**Comment by jamen** [comment]
I've done the permissions in audio.js with two teams.  
 - Devs team: Create branches on repos and pull request them to master branch, cannot push to master.
 - Core team: Merge the pull requests to master after review.

Feel free to invite people to the devs team as you see fit.

**Comment by dfcreative** [comment]
@jamen ok, there are not too many audio guys in js though )

**Comment by dfcreative** [comment]
Btw I would suggest adding _contributing_ project to keep some guidelines, naming conventions, gitter link etc.

**Comment by dfcreative** [comment]
Ok, guess it is done)

**Comment by jamen** [comment]
Awesome.  :+1:
